<?php

/**
 * This is the model base class for the table "members".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Members".
 *
 * Columns in table "members" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $firstname
 * @property string $lastname
 * @property string $email
 * @property string $city
 * @property string $address
 * @property string $zip
 * @property string $mobile_phone
 * @property string $phone
 * @property string $description
 * @property string $status
 * @property string $username
 * @property string $password
 *
 */
abstract class BaseMembers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'members';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Members|Members', $n);
	}

	public static function representingColumn() {
		return 'firstname';
	}

	public function rules() {
		return array(
			array('firstname, lastname, email, username, password', 'required'),
			array('firstname, lastname, city', 'length', 'max'=>45),
			array('email', 'length', 'max'=>80),
			array('address', 'length', 'max'=>100),
			array('zip', 'length', 'max'=>8),
			array('mobile_phone, phone, username, password', 'length', 'max'=>20),
			array('status', 'length', 'max'=>6),
			array('description', 'safe'),
			array('city, address, zip, mobile_phone, phone, description, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, firstname, lastname, email, city, address, zip, mobile_phone, phone, description, status, username, password', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'firstname' => Yii::t('app', 'Firstname'),
			'lastname' => Yii::t('app', 'Lastname'),
			'email' => Yii::t('app', 'Email'),
			'city' => Yii::t('app', 'City'),
			'address' => Yii::t('app', 'Address'),
			'zip' => Yii::t('app', 'Zip'),
			'mobile_phone' => Yii::t('app', 'Mobile Phone'),
			'phone' => Yii::t('app', 'Phone'),
			'description' => Yii::t('app', 'Description'),
			'status' => Yii::t('app', 'Status'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('zip', $this->zip, true);
		$criteria->compare('mobile_phone', $this->mobile_phone, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}