<?php

/**
 * This is the model base class for the table "members_groups".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MembersGroups".
 *
 * Columns in table "members_groups" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $group_id
 * @property string $member_id
 *
 */
abstract class BaseMembersGroups extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'members_groups';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MembersGroups|MembersGroups', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('group_id, member_id', 'required'),
			array('group_id, member_id', 'length', 'max'=>11),
			array('id, group_id, member_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'group_id' => Yii::t('app', 'Group'),
			'member_id' => Yii::t('app', 'Member'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('group_id', $this->group_id, true);
		$criteria->compare('member_id', $this->member_id, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}