<?php

/**
 * This is the model base class for the table "groups".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Groups".
 *
 * Columns in table "groups" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 * @property string $specifications
 * @property string $parent_id
 * @property integer $hide
 * @property integer $system
 *
 */
abstract class BaseGroups extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'groups';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Groups|Groups', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('hide, system', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('parent_id', 'length', 'max'=>11),
			array('description, specifications', 'safe'),
			array('description, specifications, parent_id, hide, system', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, specifications, parent_id, hide, system', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'specifications' => Yii::t('app', 'Specifications'),
			'parent_id' => Yii::t('app', 'Parent'),
			'hide' => Yii::t('app', 'Hide'),
			'system' => Yii::t('app', 'System'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('specifications', $this->specifications, true);
		$criteria->compare('parent_id', $this->parent_id, true);
		$criteria->compare('hide', $this->hide);
		$criteria->compare('system', $this->system);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}